export interface IIframe {
	url: string,
	allowFullScreen?: boolean,
	position?: "relative" | "absolute" | "fixed" | "sticky" | "static" | "inherit" | "initial" | "unset",
	display?: "block" | "none" | "inline",
	height?: string,
	width?: string,
	loading?: "auto" | "eager" | "lazy",
	target?: string,
	overflow?: string,
	styles?: object,
	name?: string,
	onLoad?: () => void,
	onMouseOver?: () => void,
	onMouseOut?: () => void,
	frameBorder?: number,
	scrolling?: string,
	id?: string,
	ariaHidden?: boolean,
	ariaLabel?: string,
	ariaLabelledby?: string,
	sandbox?: string,
	allow?: string,
	className?: string,
	title?: string
}
